# Generated by Django 5.1.7 on 2025-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='remark',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
    ]
