# Generated by Django 5.1.7 on 2025-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_meeting_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
