# Generated by Django 5.1.7 on 2025-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_client_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('SIP', 'Systematic Investment Plan'), ('LUMP', 'Lumpsum'), ('LI', 'Life Insurance'), ('TI', 'Term Insurance'), ('PMS', 'Portfolio Management Service'), ('AIF', 'Alternative Investment Fund'), ('WILL', 'Will'), ('GI', 'General insurance')], max_length=10),
        ),
    ]
