# Generated by Django 5.1.7 on 2025-03-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='fund_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
